# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c982fe886d9e590e12f3889e07c9ea76723d26856d7891fa9e0d2f6ddc2ed0d244448d04e35e62a24fdf4e53eb88129d50f83358bf3be88b1938c2b86c6ad9a2

test:
  secret_key_base: 0d897d1a7a099a1680101d58a167c5b701b52cce2ec702c8713ccc0e13627e35001a314b103621cd7b62f3e258746b37b82c4f4713071e0431f3f48fa383311a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
